# Generated by Django 2.2.1 on 2019-05-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herald', '0006_auto_20190503_0625'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sentnotification',
            name='herald_sent_sender__1d4af5_idx',
        ),
        migrations.AddField(
            model_name='sentnotification',
            name='receiver_profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='sentnotification',
            index=models.Index(fields=['sender_doctor_profile_id', 'notification_class'], name='herald_sent_sender__32b10a_idx'),
        ),
    ]
