# Generated by Django 2.2.1 on 2019-05-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herald', '0007_auto_20190503_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentnotification',
            old_name='receiver_profile_id',
            new_name='receiver_patient_profile_id',
        ),
    ]
