# Generated by Django 2.2.1 on 2019-09-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herald', '0009_sentnotification_receiver_doctor_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentnotification',
            name='sender_location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='sentnotification',
            index=models.Index(fields=['sender_location_id', 'notification_class'], name='herald_sent_sender__91ad42_idx'),
        ),
    ]
