# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-04-02 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herald', '0010_auto_20190904_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentnotification',
            name='dlt_template_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
